import org.apache.log4j.FileAppender;
import src.game.*;
import src.human.HumanInput;
import src.menace.MenaceTrainStrategy;
import src.perfect.OptimalStrategy;
import src.ui.*;
import src.game.StatesOfAnyGame;
import src.utils.FileUtils;
import src.utils.Utils;